name: mulidroid-api

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=mulidroid
      - POSTGRES_PASSWORD=mdroid
      - POSTGRES_DB=mulidroid